version: '2'
services:
  notify-gate:
    depends_on:
      - postgres
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=root
      - POSTGRES_DB=notify
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - NG_DEBUG=true
      - NG_UI_PORT=8080
    image: docker-local.jgit.me/tools-notify-gate:master
    ports:
     - 8080:8080
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=root
      - POSTGRES_DB=notify

