version: '2'
services:
  notify-gate:
    env_file:
      - .env
    depends_on:
    - postgres
    environment:
    - TZ=Europe/Moscow
    - DB_TYPE=sqlite
    - DB_PASSWORD=123
    - DB_USER=root
    - DB_NAME=notify
    - DB_HOST=postgres
    - DB_PORT=5432
    - NG_UI_PORT=8089
    - NG_INSTANCE_TITLE=dockrized instance
    image: idconstruct/notify_gate:latest
    ports:
    - 8089:8089


