version: '2'
services:
  notify-gate:
    depends_on:
    - postgres
    environment:
    - TELEGRAM_BOT_TOKEN=634913743:AAHxsE5djK6Iisq8MKBWuHx8l_jJqavdrMc
    - SLACK_AUTH_TOKEN=xoxp-35063947874-43186343684-423753368562-7dd3dfb89f6abc71bba10fcce50d81de
    - TZ=Europe/Moscow
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=root
    - POSTGRES_DB=notify
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - NG_UI_PORT=8089
    - NG_INSTANCE_TITLE=dockrized instance
    image: idconstruct/notify_gate:latest
    ports:
    - 8089:8089
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=root
    - POSTGRES_DB=notify

