version: '2'
services:
  notify-gate:
    depends_on:
      - postgres
    environment:
      - TELEGRAM_BOT_TOKEN=618643564:AAEiGErcxH8rv3x96Hd7njw0ZvIiZ85SVqk
      - SLACK_AUTH_TOKEN=xoxb-83203347009-UlQ44yvWevhJ7qjiRLwViPcr
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=root
      - POSTGRES_DB=notify
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - NG_DEBUG=true
      - NG_UI_PORT=8080
      - NG_INSTANCE_TITLE=dockrized instance
    image: docker-local.jgit.me/tools-notify-gate:0.2.0
    ports:
     - 8080:8080
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=root
      - POSTGRES_DB=notify

